"""Rebuild include/calibration_backup.h from calibration/servo_cal.json."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
JSON_PATH = ROOT.parent / "calibration" / "servo_cal.json"
HDR_PATH = ROOT / "include" / "calibration_backup.h"


def main() -> None:
    data = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    joints = data["joints"]
    if len(joints) != 18:
        raise SystemExit(f"expected 18 joints, got {len(joints)}")
    refs = ", ".join(str(int(j["ref"])) for j in joints)
    dirs = ", ".join(str(int(j["dir"])) for j in joints)
    saved = data.get("saved", "unknown")
    HDR_PATH.write_text(
        "#pragma once\n"
        "// Auto-generated from calibration/servo_cal.json — do not edit by hand.\n"
        f"// Regenerated by pca_servo_test/gen_cal_backup.py (snapshot {saved})\n\n"
        "#include <Arduino.h>\n\n"
        "static const uint8_t CAL_BACKUP_COUNT = 18;\n"
        f"static const uint16_t CAL_BACKUP_SPAN_THIGH = {int(data['locked_span_thigh'])};\n"
        f"static const uint16_t CAL_BACKUP_SPAN_SHIN = {int(data['locked_span_shin'])};\n"
        f"static const uint16_t CAL_BACKUP_REF[CAL_BACKUP_COUNT] = {{ {refs} }};\n"
        f"static const int8_t CAL_BACKUP_DIR[CAL_BACKUP_COUNT] = {{ {dirs} }};\n",
        encoding="utf-8",
    )
    print(f"wrote {HDR_PATH}")


if __name__ == "__main__":
    main()
