#pragma once
// Auto-generated from calibration/servo_cal.json — do not edit by hand.
// Regenerated by pca_servo_test/gen_cal_backup.py
// Snapshot date: 2026-08-17 (ESP32 NVS)

#include <Arduino.h>

static const uint8_t CAL_BACKUP_COUNT = 18;
static const uint16_t CAL_BACKUP_SPAN_THIGH = 226;
static const uint16_t CAL_BACKUP_SPAN_SHIN = 203;
static const uint16_t CAL_BACKUP_REF[CAL_BACKUP_COUNT] = { 295, 384, 283, 321, 306, 488, 308, 357, 473, 340, 346, 504, 346, 317, 342, 299, 479, 419 };
static const int8_t CAL_BACKUP_DIR[CAL_BACKUP_COUNT] = { 1, -1, -1, 1, -1, -1, 1, -1, -1, 1, -1, -1, 1, -1, -1, 1, -1, -1 };
